In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('car-prices_unclean - car-prices_unclean.csv.csv')

In [3]:
data.head()

Unnamed: 0  car_ID  symboling                   CarName fueltype  \
0           0     1.0        NaN        alfa-romero giulia      gas   
1           1     2.0        3.0       alfa-romero stelvio      NaN   
2           2     NaN        NaN  alfa-romero Quadrifoglio      NaN   
3           3     4.0        2.0               audi 100 ls      gas   
4           4     NaN        2.0                audi 100ls      gas   

  aspiration doornumber      carbody drivewheel enginelocation  ...  \
0        std        two  convertible        rwd          front  ...   
1        std        two  convertible        rwd          front  ...   
2        std        two    hatchback        rwd          front  ...   
3        std       four        sedan        fwd          front  ...   
4        std       four        sedan        4wd          front  ...   

   fuelsystem  boreratio  stroke  compressionratio  horsepower peakrpm  \
0        mpfi       3.47    2.68               9.0         111    5000   
1        mpfi       3.47    2.68               9.0         111    5000   
2        mpfi       2.68    3.47               9.0         154    5000   
3        mpfi       3.19    3.40              10.0         102    5500   
4        mpfi       3.19    3.40               8.0         115    5500   

  citympg  highwaympg    price  Untitled  
0      21          27  13495.0       NaN  
1      21          27  16500.0       NaN  
2      19          26  16500.0       NaN  
3      24          30  13950.0       NaN  
4      18          22  17450.0       NaN  

[5 rows x 28 columns]

In [4]:
data.shape

(205, 28)

In [5]:
data.info

<bound method DataFrame.info of      Unnamed: 0  car_ID  symboling                   CarName fueltype  \
0             0     1.0        NaN        alfa-romero giulia      gas   
1             1     2.0        3.0       alfa-romero stelvio      NaN   
2             2     NaN        NaN  alfa-romero Quadrifoglio      NaN   
3             3     4.0        2.0               audi 100 ls      gas   
4             4     NaN        2.0                audi 100ls      gas   
..          ...     ...        ...                       ...      ...   
200         200   201.0       -1.0           volvo 145e (sw)      gas   
201         201   202.0        NaN               volvo 144ea      NaN   
202         202   203.0        NaN               volvo 244dl      gas   
203         203     NaN        NaN                 volvo 246   diesel   
204         204   205.0       -1.0               volvo 264gl      gas   

    aspiration doornumber      carbody drivewheel enginelocation  ...  \
0          std    

In [6]:
data.isnull().sum()

Unnamed: 0            0
car_ID               41
symboling            41
CarName               0
fueltype             41
aspiration            0
doornumber            0
carbody               0
drivewheel            0
enginelocation        0
wheelbase             0
carlength             0
carwidth              0
carheight             0
curbweight            0
enginetype            0
cylindernumber        0
enginesize            0
fuelsystem            0
boreratio             0
stroke                0
compressionratio      0
horsepower            0
peakrpm               0
citympg               0
highwaympg            0
price                41
Untitled            205
dtype: int64

In [7]:
data.duplicated().sum()

0

In [8]:
data.duplicated().sum()

0

In [9]:
data.describe()

Unnamed: 0      car_ID   symboling   wheelbase   carlength    carwidth  \
count  205.000000  164.000000  164.000000  205.000000  205.000000  205.000000   
mean   102.000000  105.707317    0.841463   98.756585  174.049268   65.907805   
std     59.322565   59.278792    1.257805    6.021776   12.337289    2.145204   
min      0.000000    1.000000   -2.000000   86.600000  141.100000   60.300000   
25%     51.000000   57.750000    0.000000   94.500000  166.300000   64.100000   
50%    102.000000  105.500000    1.000000   97.000000  173.200000   65.500000   
75%    153.000000  159.250000    2.000000  102.400000  183.100000   66.900000   
max    204.000000  205.000000    3.000000  120.900000  208.100000   72.300000   

        carheight   curbweight  enginesize   boreratio      stroke  \
count  205.000000   205.000000  205.000000  205.000000  205.000000   
mean    53.724878  2555.565854  126.907317    3.329756    3.255415   
std      2.443522   520.680204   41.642693    0.270844    0.313597   
min     47.800000  1488.000000   61.000000    2.540000    2.070000   
25%     52.000000  2145.000000   97.000000    3.150000    3.110000   
50%     54.100000  2414.000000  120.000000    3.310000    3.290000   
75%     55.500000  2935.000000  141.000000    3.580000    3.410000   
max     59.800000  4066.000000  326.000000    3.940000    4.170000   

       compressionratio  horsepower      peakrpm     citympg  highwaympg  \
count        205.000000  205.000000   205.000000  205.000000  205.000000   
mean          10.142537  104.117073  5125.121951   25.219512   30.751220   
std            3.972040   39.544167   476.985643    6.542142    6.886443   
min            7.000000   48.000000  4150.000000   13.000000   16.000000   
25%            8.600000   70.000000  4800.000000   19.000000   25.000000   
50%            9.000000   95.000000  5200.000000   24.000000   30.000000   
75%            9.400000  116.000000  5500.000000   30.000000   34.000000   
max           23.000000  288.000000  6600.000000   49.000000   54.000000   

              price  Untitled  
count    164.000000       0.0  
mean   13546.644311       NaN  
std     7986.947115       NaN  
min     5118.000000       NaN  
25%     7957.000000       NaN  
50%    10798.000000       NaN  
75%    16506.000000       NaN  
max    41315.000000       NaN

In [10]:
a = np.array(data['car_ID'])

In [11]:
np.mean(a)

nan

In [12]:
np.median(a)

nan

In [13]:
b = np.array(data['Unnamed: 0'])

In [14]:
np.mean(b)

102.0

In [15]:
np.median(b)

102.0

In [16]:
np.max(b)

204

In [17]:
np.min(b)

0

In [18]:
np.std(b)

59.177698502053964

In [19]:
np.var(b)

3502.0

In [20]:
c= np.array(data["price"])

In [21]:
c

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
             nan,       nan,  5399.   ,  6529.   ,       nan,  7295.   ,
        7295.   ,       nan,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,       nan,  8916.5  ,  8916.5  ,       nan, 32250.   ,
       35550.   ,       nan,  5195.   ,       nan,       nan,       nan,
        7395.   ,       nan, 11845.   , 13645.   , 15645.   ,  8845.   ,
             nan, 10595.   , 10245.   ,       nan, 11245.   ,       nan,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   ,       nan, 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [22]:
np.mean(c)

nan

In [23]:
np.median(c)

nan

In [24]:
np.std(c)

nan

In [25]:
e = np.array(data['wheelbase'])

In [26]:
e

array([ 88.6,  88.6,  94.5,  99.8,  99.4,  99.8, 105.8, 105.8, 105.8,
        99.5, 101.2, 101.2, 101.2, 101.2, 103.5, 103.5, 103.5, 110. ,
        88.4,  94.5,  94.5,  93.7,  93.7,  93.7,  93.7,  93.7,  93.7,
        93.7, 103.3,  95.9,  86.6,  86.6,  93.7,  93.7,  93.7,  96.5,
        96.5,  96.5,  96.5,  96.5,  96.5,  96.5,  96.5,  94.3,  94.5,
        94.5,  96. , 113. , 113. , 102. ,  93.1,  93.1,  93.1,  93.1,
        93.1,  95.3,  95.3,  95.3,  95.3,  98.8,  98.8,  98.8,  98.8,
        98.8,  98.8, 104.9, 104.9, 110. , 110. , 106.7, 115.6, 115.6,
        96.6, 120.9, 112. , 102.7,  93.7,  93.7,  93.7,  93. ,  96.3,
        96.3,  95.9,  95.9,  95.9,  96.3,  96.3,  96.3,  96.3,  94.5,
        94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  94.5,  95.1,
        97.2,  97.2, 100.4, 100.4, 100.4,  91.3,  91.3,  99.2, 107.9,
       107.9, 114.2, 114.2, 107.9, 107.9, 114.2, 114.2, 107.9, 107.9,
       108. ,  93.7,  93.7,  93.7,  93.7,  93.7, 103.3,  95.9,  94.5,
        89.5,  89.5,

In [27]:
np.mean(e)

98.75658536585367

In [28]:
np.median(e)

97.0

In [29]:
np.max(e)

120.9

In [30]:
np.min(e)

86.6

In [31]:
np.std(e)

6.007070472147536

In [32]:
np.var(e)

36.08489565734682

In [33]:
f = np.array(data['carlength'])

In [34]:
f

array([168.8, 168.8, 171.2, 176.6, 176.6, 177.3, 192.7, 192.7, 192.7,
       178.2, 176.8, 176.8, 176.8, 176.8, 189. , 189. , 193.8, 197. ,
       141.1, 155.9, 158.8, 157.3, 157.3, 157.3, 157.3, 157.3, 157.3,
       157.3, 174.6, 173.2, 144.6, 144.6, 150. , 150. , 150. , 163.4,
       157.1, 167.5, 167.5, 175.4, 175.4, 175.4, 169.1, 170.7, 155.9,
       155.9, 172.6, 199.6, 199.6, 191.7, 159.1, 159.1, 159.1, 166.8,
       166.8, 169. , 169. , 169. , 169. , 177.8, 177.8, 177.8, 177.8,
       177.8, 177.8, 175. , 175. , 190.9, 190.9, 187.5, 202.6, 202.6,
       180.3, 208.1, 199.2, 178.4, 157.3, 157.3, 157.3, 157.3, 173. ,
       173. , 173.2, 173.2, 173.2, 172.4, 172.4, 172.4, 172.4, 165.3,
       165.3, 165.3, 165.3, 170.2, 165.3, 165.6, 165.3, 170.2, 162.4,
       173.4, 173.4, 181.7, 184.6, 184.6, 170.7, 170.7, 178.5, 186.7,
       186.7, 198.9, 198.9, 186.7, 186.7, 198.9, 198.9, 186.7, 186.7,
       186.7, 157.3, 157.3, 157.3, 167.3, 167.3, 174.6, 173.2, 168.9,
       168.9, 168.9,

In [35]:
np.mean(f)

174.04926829268288

In [36]:
np.median(f)

173.2

In [37]:
np.max(f)

208.1

In [38]:
np.min(f)

141.1

In [39]:
np.std(f)

12.307160792874917

In [40]:
np.var(f)

151.46620678167756